# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Run Pyinstaller on windows, 7zip the resulting folder and scp it to a server

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build and publish
      env:
        DEGENNES_IP: ${{ secrets.DEGENNES_IP }}
        DEGENNES_USER: ${{ secrets.DEGENNES_USER }}
        DEGENNES_PASSWORD: ${{ secrets.DEGENNES_PASSWORD }}
      run: |
        pyinstaller -w --name=testJR testJR\__main__.py
        cd dist
        7z.exe a testJR.zip testJR
        echo "$DEGENNES_PASSWORD" | scp testJR.zip $"DEGENNES_USER"@$"DEGENNES_IP":.
        