# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Run Pyinstaller on windows, 7zip the resulting folder and scp it to a server

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build executable
      run: |
        pyinstaller -w --name=testJR testJR\__main__.py
    - name: Compress
      run: |
        cd dist
        7z.exe a testJR.zip testJR
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEGENNES_IP }}
        username: ${{ secrets.DEGENNES_USER }}
        password: ${{ secrets.DEGENNES_PASSWORD }}
        source: "dist/testJR.zip"
        target: "REPTATE_PACKAGES"
        